# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/requestgpt',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/requestgpt',
                'lib_path': 'requestgpt'},
  'syms': { 'requestgpt.classification': { 'requestgpt.classification.read_utterances': ( 'classify-utterances.html#read_utterances',
                                                                                          'requestgpt/classification.py')},
            'requestgpt.core': { 'requestgpt.core.read_prompt': ('core.html#read_prompt', 'requestgpt/core.py'),
                                 'requestgpt.core.run_model': ('core.html#run_model', 'requestgpt/core.py')}}}
