# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/requestgpt',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/requestgpt',
                'lib_path': 'requestgpt'},
  'syms': {'requestgpt.core': {'requestgpt.core.show_df': ('core.html#show_df', 'requestgpt/core.py')}}}
