# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_classify-utterances.ipynb.

# %% auto 0
__all__ = ['read_utterances']

# %% ../nbs/01_classify-utterances.ipynb 2
import pandas as pd

from langchain.pydantic_v1 import BaseModel, Field
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.chains.openai_functions import create_structured_output_runnable

from tqdm.notebook import tqdm

# %% ../nbs/01_classify-utterances.ipynb 4
def read_utterances(fpath: str='../in/utterances_train.csv') -> pd.DataFrame:
	utterances = pd.read_csv(fpath)
	# set empty cells in the `label` column, which represent non-requests, to the value `0`
	utterances['label'] = utterances['label'].fillna(0).astype(int)
	return utterances
