# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['show_df']

# %% ../nbs/00_core.ipynb 3
import pandas as pd
import numpy as np

# %% ../nbs/00_core.ipynb 4
def show_df():
	return pd.DataFrame(np.random.rand(10, 5))
