# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_prompt', 'run_model']

# %% ../nbs/00_core.ipynb 9
def read_prompt(fpath):
    with open(fpath, 'r') as f:
        prompt = f.read()
    return prompt

# %% ../nbs/00_core.ipynb 55
from tqdm import tqdm

def run_model(ai, df):
	tqdm.pandas()
	ai_labels = df['text'].progress_apply(lambda x: ai(str(x), output_schema=output_request))
	# Unpack the dictionary in `gpt_dict` column into separate columns and prefix every column with `gpt_`
	return pd.concat([df, ai_labels.apply(pd.Series).add_prefix('gpt_')], axis=1)
