# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_src.ipynb.

# %% auto 0
__all__ = ['load_data']

# %% ../nbs/01_src.ipynb 4
import pandas as pd

# %% ../nbs/01_src.ipynb 5
def load_data(fp='../in/utterances_requests_50k_labeled.csv'):
	df = pd.read_csv('../in/utterances_requests_50k_labeled.csv')
	# in the `label` column, replace `1.0` with `1` and `NaN` with `0`
	df["label"] = df["label"].fillna(0).astype(int)
	return df
